apiVersion: v1
kind: ReplicationController
metadata:
  name: echoheaders-default-uv
  namespace: test
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: echoheaders-default-uv
    spec:
      containers:
      - name: echoheaders-default-uv
        image: gcr.io/google_containers/echoserver:1.0
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: echoheaders-default-uv
  labels:
    app: echoheaders-default-uv
  namespace: test
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30305
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: echoheaders-default-uv
