apiVersion: v1
kind: Service
metadata:
  name: qp-ms-settings-service
spec:
  ports:
  - port: 8080
    targetPort: php-app-ports
    protocol: TCP
  selector:
    app: qp-ms-settings
  type: LoadBalancer
