apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: user-validation
  labels:
    k8s-app: user-validation-deployment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        k8s-app: user-validation
    spec:
      containers:
      - name: user-validation
        image: pengyue/ms-user-validation
        ports:
        - name: ms-uv-port
          containerPort: 80
        livenessProbe:
          httpGet:
            path: /api/doc
            port: ms-nv-port
          initialDelaySeconds: 3
          periodSeconds: 5
          timeoutSeconds: 30
          successThreshold: 1
          failureThreshold: 3
