apiVersion: v1
kind: Service
metadata:
  name: user-validation-service
spec:
  ports:
  - port: 80
    targetPort: ms-uv-port
    protocol: TCP
  selector:
    k8s-app: user-validation
  type: LoadBalancer
