apiVersion: v1
kind: Service
metadata:
  name: publisher-registration-ui-service
spec:
  ports:
  - port: 31200
    nodePort: 31200
    targetPort: pru-port
    protocol: TCP
  selector:
    app: publisher-registration-ui
  type: NodePort
