apiVersion: v1
kind: Service
metadata:
  name: publisher-registration-api-service
spec:
  ports:
  - port: 31100
    nodePort: 31100
    targetPort: pra-port
    protocol: TCP
  selector:
    app: publisher-registration-api
  type: NodePort
